steps:
  - id: go-version
    name: 'gcr.io/cloud-builders/go:debian'
    env: ['GOPATH=/workspace/_gopath', 'GO111MODULE=on']
    args: ['version']
  - id: backend-test
    name: 'gcr.io/cloud-builders/go:debian'
    env: ['GOPATH=/workspace/_gopath', 'GO111MODULE=on']
    entrypoint: 'make'
    args: ['-C', 'backend', 'test']
  - id: backend-lint
    name: 'golangci/golangci-lint'
    entrypoint: 'make'
    args: ['-C', 'backend', 'lint']
  - id: backend-cover
    name: 'gcr.io/cloud-builders/go:debian'
    env: ['GOPATH=/workspace/_gopath', 'GO111MODULE=on']
    entrypoint: 'make'
    args: ['-C', 'backend', 'check-coverage']
